// <auto-generated />
using System;
using FarmAndFriends.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmAndFriends.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816155338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.CropCareCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CareOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CaredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CaredByUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CoinsAfter")
                        .HasColumnType("integer");

                    b.Property<int>("CoinsGained")
                        .HasColumnType("integer");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorFarmCareCycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitorUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpGained")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("CareOpportunityId", "CaredAt");

                    b.HasIndex("VisitorFarmCareCycleId", "CareOpportunityId");

                    b.HasIndex("VisitorUserId", "CaredAt");

                    b.HasIndex("VisitorUserId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("VisitorUserId", "CareOpportunityId", "CaredAt");

                    b.HasIndex("VisitorUserId", "OwnerUserId", "CaredAt");

                    b.ToTable("CropCareCompletions");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastPestInfestationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("UserBId");

                    b.HasIndex("Status", "RequestedByUserId");

                    b.HasIndex("UserAId", "UserBId")
                        .IsUnique();

                    b.ToTable("Friendships", t =>
                        {
                            t.HasCheckConstraint("CK_Friendships_DifferentUsers", "\"UserAId\" <> \"UserBId\"");

                            t.HasCheckConstraint("CK_Friendships_RequesterIsParticipant", "\"RequestedByUserId\" = \"UserAId\" OR \"RequestedByUserId\" = \"UserBId\"");
                        });
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<int>("PremiumCoins")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Inventories", t =>
                        {
                            t.HasCheckConstraint("CK_Inventories_Coins_NonNegative", "\"Coins\" >= 0");

                            t.HasCheckConstraint("CK_Inventories_PremiumCoins_NonNegative", "\"PremiumCoins\" >= 0");
                        });
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.LandPurchaseCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddedPlotCount")
                        .HasColumnType("integer");

                    b.Property<int>("AmountSpent")
                        .HasColumnType("integer");

                    b.Property<Guid>("BuyerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CoinsAfter")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpandedHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpandedWidth")
                        .HasColumnType("integer");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlotNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PremiumCoinsAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlotId")
                        .IsUnique();

                    b.HasIndex("BuyerUserId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("FarmId", "BuyerUserId");

                    b.HasIndex("FarmId", "PlotNumber")
                        .IsUnique();

                    b.HasIndex("PlotId", "FarmId");

                    b.ToTable("LandPurchaseCompletions", t =>
                        {
                            t.HasCheckConstraint("CK_LandPurchaseCompletions_AmountSpent_Positive", "\"AmountSpent\" > 0");

                            t.HasCheckConstraint("CK_LandPurchaseCompletions_CoinsAfter_NonNegative", "\"CoinsAfter\" >= 0");

                            t.HasCheckConstraint("CK_LandPurchaseCompletions_ExpansionMetadata_Consistent", "(\"PlotNumber\" = 9 AND \"AddedPlotCount\" = 19 AND \"ExpandedWidth\" = 7 AND \"ExpandedHeight\" = 4) OR (\"PlotNumber\" <> 9 AND \"AddedPlotCount\" = 0 AND \"ExpandedWidth\" IS NULL AND \"ExpandedHeight\" IS NULL)");

                            t.HasCheckConstraint("CK_LandPurchaseCompletions_PaymentCurrency_Valid", "\"PaymentCurrency\" IN ('coins', 'premiumCoins')");

                            t.HasCheckConstraint("CK_LandPurchaseCompletions_PlotNumber_Range", "\"PlotNumber\" >= 7 AND \"PlotNumber\" <= 28");

                            t.HasCheckConstraint("CK_LandPurchaseCompletions_PremiumCoinsAfter_NonNegative", "\"PremiumCoinsAfter\" >= 0");
                        });
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CareOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FriendshipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid?>("PestPlotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TheftLogId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CareOpportunityId")
                        .IsUnique();

                    b.HasIndex("FriendshipId");

                    b.HasIndex("TheftLogId")
                        .IsUnique();

                    b.HasIndex("PestPlotId", "CreatedAt");

                    b.HasIndex("RecipientUserId", "ReadAt", "CreatedAt");

                    b.HasIndex("Type", "ActorUserId", "CreatedAt");

                    b.HasIndex("Type", "ActorUserId", "RecipientUserId", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.PestRemovalCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CoinsAfter")
                        .HasColumnType("integer");

                    b.Property<int>("CoinsGained")
                        .HasColumnType("integer");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PestOccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RemainingYieldAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("XpGained")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PestOccurrenceId")
                        .IsUnique();

                    b.HasIndex("ActorUserId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ActorUserId", "RemovedAt");

                    b.ToTable("PestRemovalCompletions", t =>
                        {
                            t.HasCheckConstraint("CK_PestRemovalCompletions_CoinsAfter_NonNegative", "\"CoinsAfter\" >= 0");

                            t.HasCheckConstraint("CK_PestRemovalCompletions_CoinsGained_NonNegative", "\"CoinsGained\" >= 0");

                            t.HasCheckConstraint("CK_PestRemovalCompletions_RemainingYield_Positive", "\"RemainingYieldAfter\" IS NULL OR \"RemainingYieldAfter\" >= 1");

                            t.HasCheckConstraint("CK_PestRemovalCompletions_XpGained_NonNegative", "\"XpGained\" >= 0");
                        });
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CareOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PestAppearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PestAppearsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PestConsumedAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PestConsumesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PestOccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PestResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PestScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("PestType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProtectedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RemainingYield")
                        .HasColumnType("integer");

                    b.Property<string>("SeedId")
                        .HasColumnType("text");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CareOpportunityId")
                        .IsUnique();

                    b.HasIndex("PestOccurrenceId");

                    b.HasIndex("FarmId", "X", "Y")
                        .IsUnique();

                    b.ToTable("Plots", t =>
                        {
                            t.HasCheckConstraint("CK_Plots_Coordinates_NonNegative", "\"X\" >= 0 AND \"Y\" >= 0");

                            t.HasCheckConstraint("CK_Plots_PestConsumedAmount_NonNegative", "\"PestConsumedAmount\" >= 0");

                            t.HasCheckConstraint("CK_Plots_RemainingYield_Positive", "\"RemainingYield\" IS NULL OR \"RemainingYield\" >= 1");
                        });
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Seed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("integer");

                    b.Property<int>("CropAmount")
                        .HasColumnType("integer");

                    b.Property<string>("CropId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GrowTime")
                        .HasColumnType("double precision");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SellPrice")
                        .HasColumnType("integer");

                    b.Property<int>("TheftChancePercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seeds");

                    b.HasData(
                        new
                        {
                            Id = "carrot",
                            BuyPrice = 10,
                            CropAmount = 1,
                            CropId = "carrot_crop",
                            GrowTime = 300.0,
                            Icon = "🥕",
                            MinLevel = 1,
                            Name = "Cenoura",
                            SellPrice = 20,
                            TheftChancePercent = 100
                        },
                        new
                        {
                            Id = "corn",
                            BuyPrice = 20,
                            CropAmount = 3,
                            CropId = "corn_crop",
                            GrowTime = 120.0,
                            Icon = "🌽",
                            MinLevel = 2,
                            Name = "Milho",
                            SellPrice = 45,
                            TheftChancePercent = 100
                        },
                        new
                        {
                            Id = "tomato",
                            BuyPrice = 30,
                            CropAmount = 4,
                            CropId = "tomato_crop",
                            GrowTime = 120.0,
                            Icon = "🍅",
                            MinLevel = 3,
                            Name = "Tomate",
                            SellPrice = 60,
                            TheftChancePercent = 100
                        },
                        new
                        {
                            Id = "pumpkin",
                            BuyPrice = 40,
                            CropAmount = 5,
                            CropId = "pumpkin_crop",
                            GrowTime = 120.0,
                            Icon = "🎃",
                            MinLevel = 4,
                            Name = "Abóbora",
                            SellPrice = 80,
                            TheftChancePercent = 100
                        });
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.VisitorFarmCareCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CoinsReward")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RewardGranted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VisitorUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("VisitorUserId", "FarmId", "StartedAt");

                    b.HasIndex("VisitorUserId", "FarmId", "RewardGranted", "StartedAt")
                        .HasDatabaseName("IX_CareCycles_Visitor_Farm_Rewarded_StartedAt");

                    b.ToTable("VisitorFarmCareCycles", t =>
                        {
                            t.HasCheckConstraint("CK_VisitorFarmCareCycles_DifferentUsers", "\"VisitorUserId\" <> \"OwnerUserId\"");

                            t.HasCheckConstraint("CK_VisitorFarmCareCycles_ValidWindow", "\"EndsAt\" > \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("TheftLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("GotBonus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SeedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThiefUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.HasIndex("SeedId");

                    b.HasIndex("ThiefUserId");

                    b.HasIndex("FarmId", "ThiefUserId", "CreatedAt");

                    b.ToTable("TheftLogs");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.CropCareCompletion", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.VisitorFarmCareCycle", "VisitorFarmCareCycle")
                        .WithMany("Completions")
                        .HasForeignKey("VisitorFarmCareCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "VisitorUser")
                        .WithMany()
                        .HasForeignKey("VisitorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");

                    b.Navigation("VisitorFarmCareCycle");

                    b.Navigation("VisitorUser");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Farm", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "User")
                        .WithMany("Farms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedByUser");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.LandPurchaseCompletion", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "BuyerUser")
                        .WithMany()
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId", "BuyerUserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId", "FarmId")
                        .HasPrincipalKey("Id", "FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyerUser");

                    b.Navigation("Farm");

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Friendship", "Friendship")
                        .WithMany()
                        .HasForeignKey("FriendshipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheftLog", "TheftLog")
                        .WithMany()
                        .HasForeignKey("TheftLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");

                    b.Navigation("Friendship");

                    b.Navigation("RecipientUser");

                    b.Navigation("TheftLog");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.PestRemovalCompletion", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Plot", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Farm", "Farm")
                        .WithMany("Plots")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.VisitorFarmCareCycle", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "VisitorUser")
                        .WithMany()
                        .HasForeignKey("VisitorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("OwnerUser");

                    b.Navigation("VisitorUser");
                });

            modelBuilder.Entity("TheftLog", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Seed", "Seed")
                        .WithMany()
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "ThiefUser")
                        .WithMany()
                        .HasForeignKey("ThiefUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Plot");

                    b.Navigation("Seed");

                    b.Navigation("ThiefUser");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.VisitorFarmCareCycle", b =>
                {
                    b.Navigation("Completions");
                });
#pragma warning restore 612, 618
        }
    }
}
