// <auto-generated />
using System;
using FarmAndFriends.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmAndFriends.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<int>("PremiumCoins")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PlantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RemainingYield")
                        .HasColumnType("integer");

                    b.Property<string>("SeedId")
                        .HasColumnType("text");

                    b.Property<bool>("Unlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Seed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("integer");

                    b.Property<int>("CropAmount")
                        .HasColumnType("integer");

                    b.Property<string>("CropId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GrowTime")
                        .HasColumnType("double precision");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SellPrice")
                        .HasColumnType("integer");

                    b.Property<int>("TheftChancePercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seeds");

                    b.HasData(
                        new
                        {
                            Id = "carrot",
                            BuyPrice = 10,
                            CropAmount = 1,
                            CropId = "carrot_crop",
                            GrowTime = 300.0,
                            MinLevel = 1,
                            Name = "Cenoura",
                            SellPrice = 20,
                            TheftChancePercent = 100
                        },
                        new
                        {
                            Id = "corn",
                            BuyPrice = 20,
                            CropAmount = 3,
                            CropId = "corn_crop",
                            GrowTime = 120.0,
                            MinLevel = 2,
                            Name = "Milho",
                            SellPrice = 45,
                            TheftChancePercent = 100
                        },
                        new
                        {
                            Id = "tomato",
                            BuyPrice = 30,
                            CropAmount = 4,
                            CropId = "tomato_crop",
                            GrowTime = 120.0,
                            MinLevel = 3,
                            Name = "Tomate",
                            SellPrice = 60,
                            TheftChancePercent = 100
                        });
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TheftLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("GotBonus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SeedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThiefUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.HasIndex("SeedId");

                    b.HasIndex("ThiefUserId");

                    b.HasIndex("FarmId", "ThiefUserId", "CreatedAt");

                    b.ToTable("TheftLogs");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Farm", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "User")
                        .WithMany("Farms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Plot", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Farm", "Farm")
                        .WithMany("Plots")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheftLog", b =>
                {
                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.Seed", "Seed")
                        .WithMany()
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmAndFriends.Api.Domain.Entities.User", "ThiefUser")
                        .WithMany()
                        .HasForeignKey("ThiefUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Plot");

                    b.Navigation("Seed");

                    b.Navigation("ThiefUser");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FarmAndFriends.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
